name: chord Build & Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: |
        npm install -g gulp mocha
        yarn install

      - name: Install dependencies of Linux
        run: |
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y build-essential gcc g++ make bsdtar python-dev rpm

      - name: Build
        run: |
          yarn run compile &&
          yarn run test
